### PR TITLE
154 feature request option to dry run

### LINKED ISSUE #154: Feature request: option to dry-run
I'd like to ask to implement a feature which would allow me to run `tfswitch` in a dry-run mode where it only outputs whether it would switch terraform version in current directory or not with different exit codes for the two operations (e.g. `0` for when no switching is required and `1` for when `tfswitch` would switch versions).

My use case: we're managing different infrastructures from different repositories including legacy setups – most of these are using different versions of terraform and we're not planning to unify them. Most of the time I need to switch terraform version when I work on something in several different setups at the same time but it's not always that I need to actually switch terraform version (e.g. when I only need to cd into dir to check something) hence suggested `cdtfswitch()` Bash alias is not something I indeed need but would rather want to inject something like `tfswitch --dry-run >/dev/null || echo "tfswitch to use correct terraform version"` into my `PROMPT_COMMAND` env var so that I get notified when my Terraform version doesn't match Terraform version constraint every time I hit enter on the command line.

Thanks in advance.

### PR DESCRIPTION
**Pull request by MatrixCrawler**
Added --dry-run flag
This will fix #154

### CODE REVIEW

**Comment by MatrixCrawler** [comment]
Actually, this feature obsoletes the --show-latest-pre and --show-latest-stable flags as you can you use `tfswitch --latest-pre --dry-run` or `tfswitch --latest-stable --dry-run` 🤔

**Review by yermulnik — APPROVED** [review]
LGTM. Appreciate your time and effort.

**Comment by yermulnik** [comment]
@MatrixCrawler Apologies I haven't shouted earlier:
```shell
> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

> go run ./main.go --dry-run -u
# no output

> echo $?
0

> go run ./main.go -u
19:37:52.830 INFO Installing terraform at "/home/giermulnik/bin"
19:37:52.875 INFO Switched terraform to version "1.8.2"
```
Seems like nothing happens with `--dry-run`. What am I missing? 🤔

**Comment by yermulnik** [comment]
Also this but it's probably from something else:
```shell
> go run ./main.go --latest-pre 1.7 --dry-run
19:42:43.031 ERROR Error parsing constraint "1.7": <nil>
19:42:43.031 INFO Invalid minor terraform version format.
 Format should be #.# where # are numbers. For example, 0.11 is valid version

> go run ./main.go --latest-pre 1.7
19:41:54.254 INFO Installing terraform at "/home/giermulnik/bin"
19:41:54.336 INFO Downloading "https://releases.hashicorp.com/terraform/1.7.0-rc2/terraform_1.7.0-rc2_linux_amd64.zip"
19:41:54.336 INFO Downloading to "/home/giermulnik/.terraform.versions/terraform_1.7.0-rc2_linux_amd64.zip"
19:41:56.620 INFO 25939409 bytes downloaded
19:41:56.620 INFO Downloading "https://releases.hashicorp.com/terraform/1.7.0-rc2/terraform_1.7.0-rc2_SHA256SUMS"
19:41:56.620 INFO Downloading to "/home/giermulnik/.terraform.versions/terraform_1.7.0-rc2_SHA256SUMS"
19:41:57.343 INFO 1434 bytes downloaded
19:41:57.343 INFO Downloading "https://releases.hashicorp.com/terraform/1.7.0-rc2/terraform_1.7.0-rc2_SHA256SUMS.72D7468F.sig"
19:41:57.343 INFO Downloading to "/home/giermulnik/.terraform.versions/terraform_1.7.0-rc2_SHA256SUMS.72D7468F.sig"
19:41:57.420 INFO 566 bytes downloaded
19:41:57.420 INFO Verifying signature of checksum file...
19:41:57.427 INFO Checksum file signature verification successful.
19:41:57.485 INFO Deleting "/home/giermulnik/.terraform.versions/terraform_1.7.0-rc2_SHA256SUMS"
19:41:57.485 INFO Deleting "/home/giermulnik/.terraform.versions/terraform_1.7.0-rc2_SHA256SUMS.72D7468F.sig"
19:41:57.901 INFO Switched terraform to version "1.7.0-rc2"
19:41:57.901 ERROR Error parsing constraint "1.7": <nil>
19:41:57.901 INFO Invalid minor terraform version format.
 Format should be #.# where # are numbers. For example, 0.11 is valid version
```
The errors looks odd 😕

**Pull request merged**
