### PR TITLE
Fix Windows

### PR DESCRIPTION
**Pull request by ziggy471**
Fix binpath
Fix arrow keys

### CODE REVIEW

**Comment by ziggy471** [comment]
Fix #199

**Review by yermulnik — APPROVED** [review]
Looks good.

**Comment by sworisbreathing** [comment]
ping @Jukie @warrensbox  - any chance of getting a review on this one any time soon? I'm keen to move from my homegrown scripts to tfswitch but not sure it'll work on windows without this PR

**Comment by ionstormadi** [comment]
ping @Jukie @warrensbox  - any chance of getting a review on this one any time soon please.

**Comment by Navacio** [comment]
Any chance we can get this pulled in? I can continue to cherry pick but its no fun. @warrensbox @jukie

**Comment by warrensbox** [comment]
Will merge by this week '

**Comment by sworisbreathing** [comment]
Thanks @warrensbox. Will #267 also be reviewed/merged?

**Comment by yermulnik** [comment]
@ziggy471 Apologies for this PR left unmerged =( Has by any chance the https://github.com/warrensbox/terraform-switcher/pull/327 resolved what this PR of yours was meant for? If not, please re-open.

**Comment by ziggy471** [comment]
@yermulnik Haven't even bothered checking the other PR, we gave up trying to have the IT guys manage TF, now just DevOps,, so no need for Windows anymore.  This was just my 5 minute attempt to make it work on their machines.

**Comment by systematicguy** [comment]
Respectfully, I am very much anticipating a fix for windows. ^^

**Comment by systematicguy** [comment]
Tested v1.1.1, works now! Thank you!

**Pull request closed without merging**
