### PR TITLE
Make leading slash optional in regex when looking for versions

### PR DESCRIPTION
**Pull request by tusv**
Trying to solve https://github.com/warrensbox/terraform-switcher/issues/311

### CODE REVIEW

**Review by yermulnik — COMMENTED** [review]
Might probably make sense to apply custom regex for when custom mirror endpoint is passed by means of cmdline flag. Ideally identify whether endpoint is Artifactory and use custom regex to only apply in this case.
Does it sounds sensible?

**Comment by tusv** [comment]
@yermulnik I could do that. But, in this case since the fix does not break existing behavior I am hoping we can keep it simple.

I am also guessing that this may not be artifactory specific and any other repository/mirror that relies on auto index browsing is likely to behave this way.

**Comment by yermulnik** [comment]
@tusv Then first of the suggested options fits this use case. My only intention is to keep as much compatibility as possible, hence applying custom regex for when `mirror` cmdline option is specified sounds reasonable to me.

Hope @warrensbox and @jukie would have an opportunity to weigh too though.

**Comment by MatrixCrawler** [comment]
This looks good to me @yermulnik 
The ? quantifier in the regex requires zero or one / so i don't see that this would break existing behvaiour.

**Review by MatrixCrawler — APPROVED** [review]

**Review by yermulnik — APPROVED** [review]

**Comment by yermulnik** [comment]
> This looks good to me @yermulnik The ? quantifier in the regex requires zero or one / so i don't see that this would break existing behvaiour.

👍🏻 Agreed.
Are we okay to merge this one?

**Comment by yermulnik** [comment]
Asking to double check as I'm a bit out of context with the old PRs =(

**Comment by tusv** [comment]
> > This looks good to me @yermulnik The ? quantifier in the regex requires zero or one / so i don't see that this would break existing behvaiour.
> 
> 👍🏻 Agreed. Are we okay to merge this one?

Yes, I just double checked just to be sure.

**Comment by yermulnik** [comment]
> > 👍🏻 Agreed. Are we okay to merge this one?
> 
> Yes, I just double checked just to be sure.

Apologies for the confusion: I intended to ask @MatrixCrawler

**Pull request merged**
