### PR TITLE
Release Workflow fix

### PR DESCRIPTION
**Pull request by MatrixCrawler**
It seems that the version update only works over the PR way. With this i try to solve that problem.

### CODE REVIEW

**Review by yermulnik — APPROVED** [review]

**Comment by MatrixCrawler** [comment]
I would like to let @warrensbox make the merge.
It might be necessary to exempt PR that are created by GitHub actions from the "needs two reviews" restrictions

**Comment by warrensbox** [comment]
Let me test this first on another repo

**Comment by warrensbox** [comment]
I cannot get this to work right

**Comment by MatrixCrawler** [comment]
You are changing the version file in the workflow, but github does not allow pushes on the master branch directly. Changes have to be done via a PR.
This fix should create a temporary release-branch, a PR and merge this PR automatically to update the Version file.

**Pull request merged**
