### PR TITLE
Upgrade to Golang 1.18

### PR DESCRIPTION
**Pull request by Jukie**
Fix working directory after revert of #232

### CODE REVIEW

**Review by yermulnik — APPROVED** [review]
LGTM

**Comment by yermulnik** [comment]
Hmm 🤔 The #234 didn't require this many approving reviews
image

**Review by yermulnik — APPROVED** [review]

**Comment by yermulnik** [comment]
Let me after all revert #234 at this time so fix build.

**Comment by yermulnik** [comment]
No luck with #236 as it requires at least 3 approving reviews to.
@warrensbox Is this change something you're aware of?

**Comment by Jukie** [comment]
It seems like the list of approvers were updated in the repo. Rolling forward with this PR will fix the builds though @warrensbox.

**Review by warrensbox — APPROVED** [review]
This should fix the broken build

**Pull request merged**
