### PR TITLE
Switch from github.com/hashicorp/hcl2 to github.com/hashicorp/hcl/v2

### PR DESCRIPTION
**Pull request by anthonyfok**
From README.md at https://github.com/hashicorp/hcl2:

> ## Experimental HCL2
>
> This repository was used for the initial development of version 2 of HCL, but is now archived because the work from this repository was incorporated back in to [the main HCL repository](https://github.com/hashicorp/hcl).
>
> This repository remains here for the moment for compatibility with existing callers that imported the experimental version. We strongly encourage switching to a stable release of HCL 2 as soon as possible. For more information on installing HCL 1 and/or HCL 2, please see [the Version Selection guide](https://github.com/hashicorp/hcl/wiki/Version-Selection).
>
> There will be no further development in this temporary experimental HCL 2 repository.

My motivation is to simplify the [Debian packaging of terraform-switcher](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014440).  Thanks!

### CODE REVIEW

**Review by yermulnik — APPROVED** [review]

**Comment by crablab** [comment]
@anthonyfok Could you resolve the conflict please, then we can get this merged? 
Apologies for the delay in getting to this PR.

**Comment by warrensbox** [comment]
Ping @anthonyfok

**Comment by MatrixCrawler** [comment]
This would be solved with #356 as is switched the packages there, too

**Comment by yermulnik** [comment]
> This would be solved with #356 as is switched the packages there, too

I'm closing this PR then.

Superseded by #356

**Pull request closed without merging**
