### PR TITLE
adjust regex to get all terraform versinos from mirror

### PR DESCRIPTION
**Pull request by chrispruitt**
This fixes https://github.com/warrensbox/terraform-switcher/issues/250 and broken unit tests.

### CODE REVIEW

**Review by llandmeyer — APPROVED** [review]

**Review by yermulnik — APPROVED** [review]
LGTM until `tfswitch` v0.14 gets released.

**Review by Jukie — APPROVED** [review]

**Comment by warrensbox** [comment]
Testing @chrispruitt's branch

**Review by warrensbox — APPROVED** [review]

**Comment by warrensbox** [comment]
I have not released it yet, it's merged to master for now.
Now I get #252 reviewed, I will release asap

**Comment by warrensbox** [comment]
Released: https://github.com/warrensbox/terraform-switcher/releases/tag/0.13.1275
Please help test the release and report any issues. 
Thanks for contributing!

**Pull request merged**
